package vete.Interfaz;

import javax.swing.JList;
import javax.swing.JOptionPane;
import vete.Entidad.Cliente;
import vete.Negocio.ControladorCliente;

/**
 *
 * @author Lisandro
 */
public class PanelClientes extends javax.swing.JPanel {

    private static final long serialVersionUID = -7678708138412181288L;

    /** Creates new form PanelClientes */
    public PanelClientes() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCliente = new javax.swing.JPanel();
        tfBuscarCliente = new javax.swing.JTextField();
        jbBuscarCliente = new javax.swing.JButton();
        spCliente = new javax.swing.JSplitPane();
        jspTablaCliente = new javax.swing.JScrollPane();
        jtCliente = new javax.swing.JTable();
        jtpCliente = new javax.swing.JTabbedPane();
        jpGeneralCliente = new javax.swing.JPanel();
        tfCodigoCliente = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfNombreCliente = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        tfCuitCliente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfNumeroTelefonoCliente = new javax.swing.JTextField();
        tfMailCliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfDescuentoCliente = new javax.swing.JTextField();
        cbEstadoDescuentoCliente = new javax.swing.JComboBox();
        cbCondicionIvaCliente = new javax.swing.JComboBox();
        jLabel67 = new javax.swing.JLabel();
        jpDomicilioCliente = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        tfCalleCliente = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfNumeroCliente = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfPisoCliente = new javax.swing.JTextField();
        tfDeptoCliente = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        cbLocalidadCliente = new javax.swing.JComboBox();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        cbProvinciaCliente = new javax.swing.JComboBox();
        cbPaisCliente = new javax.swing.JComboBox();
        jLabel59 = new javax.swing.JLabel();
        jpDetalleCliente = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jepDetalleCliente = new javax.swing.JEditorPane();
        pbCliente = new javax.swing.JPanel();
        jbNuevoCliente = new javax.swing.JButton();
        jbModificarCliente = new javax.swing.JButton();
        jbEliminarCliente = new javax.swing.JButton();
        jbImprimirCliente = new javax.swing.JButton();
        jbVenderCliente = new javax.swing.JButton();
        jbOpcionesCliente = new javax.swing.JButton();
        jbLimpiarCliente = new javax.swing.JButton();

        jpCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        tfBuscarCliente.setToolTipText("Busqueda rapida");
        tfBuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBuscarClienteKeyTyped(evt);
            }
        });

        jbBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vete/buscar1.gif"))); // NOI18N
        jbBuscarCliente.setToolTipText("Buscar");
        jbBuscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbBuscarClienteMouseClicked(evt);
            }
        });

        spCliente.setDividerLocation(100);
        spCliente.setDividerSize(10);
        spCliente.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jspTablaCliente.setPreferredSize(new java.awt.Dimension(468, 424));

        jtCliente.setFont(new java.awt.Font("Arial", 0, 12));
        jtCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nombre", "CUIT"
            }
        ));
        jtCliente.setColumnSelectionAllowed(true);
        jtCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtClienteMouseClicked(evt);
            }
        });
        jspTablaCliente.setViewportView(jtCliente);

        spCliente.setLeftComponent(jspTablaCliente);

        tfCodigoCliente.setFont(new java.awt.Font("Arial", 0, 12));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel8.setText("Código");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel11.setText("Nombre");

        tfNombreCliente.setFont(new java.awt.Font("Arial", 0, 12));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel15.setText("CUIT");

        tfCuitCliente.setFont(new java.awt.Font("Arial", 0, 12));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel12.setText("Teléfono");

        tfNumeroTelefonoCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNumeroTelefonoCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNumeroTelefonoClienteFocusLost(evt);
            }
        });

        tfMailCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel13.setText("Mail");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel14.setText("Descuento");

        tfDescuentoCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfDescuentoCliente.setText("0.0");

        cbEstadoDescuentoCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbEstadoDescuentoCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", " %" }));

        cbCondicionIvaCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbCondicionIvaCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Consumidor Final", "Responsable Inscripto" }));

        jLabel67.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel67.setText("Condición de IVA");

        javax.swing.GroupLayout jpGeneralClienteLayout = new javax.swing.GroupLayout(jpGeneralCliente);
        jpGeneralCliente.setLayout(jpGeneralClienteLayout);
        jpGeneralClienteLayout.setHorizontalGroup(
            jpGeneralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGeneralClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGeneralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGeneralClienteLayout.createSequentialGroup()
                        .addGroup(jpGeneralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpGeneralClienteLayout.createSequentialGroup()
                                .addComponent(tfDescuentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbEstadoDescuentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpGeneralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel67)
                            .addGroup(jpGeneralClienteLayout.createSequentialGroup()
                                .addComponent(cbCondicionIvaCliente, 0, 339, Short.MAX_VALUE)
                                .addGap(93, 93, 93))))
                    .addGroup(jpGeneralClienteLayout.createSequentialGroup()
                        .addGroup(jpGeneralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpGeneralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfNumeroTelefonoCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfCodigoCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addComponent(jLabel12))
                        .addGap(6, 6, 6)
                        .addGroup(jpGeneralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(tfMailCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpGeneralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCuitCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpGeneralClienteLayout.setVerticalGroup(
            jpGeneralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGeneralClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGeneralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpGeneralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCuitCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpGeneralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpGeneralClienteLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNumeroTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpGeneralClienteLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpGeneralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpGeneralClienteLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpGeneralClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDescuentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbEstadoDescuentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpGeneralClienteLayout.createSequentialGroup()
                        .addComponent(jLabel67)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCondicionIvaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jtpCliente.addTab("General", jpGeneralCliente);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel16.setText("Calle");

        tfCalleCliente.setFont(new java.awt.Font("Arial", 0, 12));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel17.setText("Numero");

        tfNumeroCliente.setFont(new java.awt.Font("Arial", 0, 12));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel18.setText("Piso");

        tfPisoCliente.setFont(new java.awt.Font("Arial", 0, 12));

        tfDeptoCliente.setFont(new java.awt.Font("Arial", 0, 12));

        jLabel55.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel55.setText("Depto");

        jLabel56.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel56.setText("Localidad");

        cbLocalidadCliente.setFont(new java.awt.Font("Arial", 0, 12));
        cbLocalidadCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Capital", "Las Heras", "Guaymallén", "Godoy Cruz" }));

        jLabel58.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel58.setText("Provincia");

        cbProvinciaCliente.setFont(new java.awt.Font("Arial", 0, 12));
        cbProvinciaCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Mendoza", "Córdoba", "Buenos Aires", "Tucuman" }));

        cbPaisCliente.setFont(new java.awt.Font("Arial", 0, 12));
        cbPaisCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Argentina", "Bolivia", "Chile", "Brasil" }));

        jLabel59.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel59.setText("País");

        javax.swing.GroupLayout jpDomicilioClienteLayout = new javax.swing.GroupLayout(jpDomicilioCliente);
        jpDomicilioCliente.setLayout(jpDomicilioClienteLayout);
        jpDomicilioClienteLayout.setHorizontalGroup(
            jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDomicilioClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDomicilioClienteLayout.createSequentialGroup()
                        .addGroup(jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDomicilioClienteLayout.createSequentialGroup()
                                .addComponent(cbLocalidadCliente, 0, 164, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jpDomicilioClienteLayout.createSequentialGroup()
                                .addComponent(jLabel56)
                                .addGap(92, 92, 92)))
                        .addGroup(jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel58)
                            .addComponent(cbProvinciaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDomicilioClienteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                                .addComponent(jLabel57)
                                .addGap(217, 217, 217))
                            .addGroup(jpDomicilioClienteLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbPaisCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel59))
                                .addGap(273, 273, 273))))
                    .addGroup(jpDomicilioClienteLayout.createSequentialGroup()
                        .addGroup(jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(tfCalleCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNumeroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPisoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDeptoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(265, 265, 265))))
        );
        jpDomicilioClienteLayout.setVerticalGroup(
            jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDomicilioClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDomicilioClienteLayout.createSequentialGroup()
                        .addGroup(jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNumeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCalleCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpDomicilioClienteLayout.createSequentialGroup()
                        .addGroup(jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel55))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPisoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDeptoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpDomicilioClienteLayout.createSequentialGroup()
                        .addGroup(jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel56)
                                .addComponent(jLabel57))
                            .addComponent(jLabel58))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpDomicilioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(cbLocalidadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbPaisCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbProvinciaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel59))
                .addGap(154, 154, 154))
        );

        jtpCliente.addTab("Domicilio", jpDomicilioCliente);

        jepDetalleCliente.setFont(new java.awt.Font("Arial", 0, 12));
        jScrollPane10.setViewportView(jepDetalleCliente);

        javax.swing.GroupLayout jpDetalleClienteLayout = new javax.swing.GroupLayout(jpDetalleCliente);
        jpDetalleCliente.setLayout(jpDetalleClienteLayout);
        jpDetalleClienteLayout.setHorizontalGroup(
            jpDetalleClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetalleClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10)
                .addContainerGap())
        );
        jpDetalleClienteLayout.setVerticalGroup(
            jpDetalleClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetalleClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtpCliente.addTab("Detalle", jpDetalleCliente);

        spCliente.setBottomComponent(jtpCliente);

        pbCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        jbNuevoCliente.setBackground(new java.awt.Color(255, 255, 255));
        jbNuevoCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbNuevoCliente.setText("Nuevo");
        jbNuevoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbNuevoClienteMouseClicked(evt);
            }
        });
        jbNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoClienteActionPerformed(evt);
            }
        });

        jbModificarCliente.setFont(new java.awt.Font("Arial", 0, 12));
        jbModificarCliente.setText("Modificar");
        jbModificarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbModificarClienteMouseClicked(evt);
            }
        });

        jbEliminarCliente.setFont(new java.awt.Font("Arial", 0, 12));
        jbEliminarCliente.setText("Eliminar");
        jbEliminarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbEliminarClienteMouseClicked(evt);
            }
        });

        jbImprimirCliente.setFont(new java.awt.Font("Arial", 0, 12));
        jbImprimirCliente.setText("Imprimir");

        jbVenderCliente.setFont(new java.awt.Font("Arial", 0, 12));
        jbVenderCliente.setText("Vender");

        jbOpcionesCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbOpcionesCliente.setText("Opciones");

        jbLimpiarCliente.setFont(new java.awt.Font("Arial", 0, 12));
        jbLimpiarCliente.setText("Limpiar");
        jbLimpiarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pbClienteLayout = new javax.swing.GroupLayout(pbCliente);
        pbCliente.setLayout(pbClienteLayout);
        pbClienteLayout.setHorizontalGroup(
            pbClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pbClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbImprimirCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jbEliminarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jbModificarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jbNuevoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jbOpcionesCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jbVenderCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jbLimpiarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addContainerGap())
        );
        pbClienteLayout.setVerticalGroup(
            pbClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbModificarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbImprimirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbVenderCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbLimpiarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jbOpcionesCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpClienteLayout = new javax.swing.GroupLayout(jpCliente);
        jpCliente.setLayout(jpClienteLayout);
        jpClienteLayout.setHorizontalGroup(
            jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpClienteLayout.createSequentialGroup()
                        .addComponent(spCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpClienteLayout.createSequentialGroup()
                        .addComponent(tfBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpClienteLayout.setVerticalGroup(
            jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pbCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfBuscarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarClienteKeyTyped
//
//        HashMap<String,Object> cliente = new HashMap<String,Object>();
//
//        //Se arma el hash con los datos del Cliente
//        cliente.put("codigo", "");
//        cliente.put("nombre", (tfBuscarCliente.getText() == null ? "" : tfBuscarCliente.getText()));
//        cliente.put("cuit", "");
//        cliente.put("mail", "");
//        cliente.put("descuento", new Double(0d));
//        cliente.put("condicionIva", "");
//
//        //Realiza la verdadera busqueda
//        this.clientes = ControladorCliente.getInstancia().buscar(cliente);
//
//        //Cargar la busqueda en la JTable
//        cargarJTableCliente(clientes);
    }//GEN-LAST:event_tfBuscarClienteKeyTyped

    private void jbBuscarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbBuscarClienteMouseClicked
//
//        //Crea una hash con todos los datos del cliente introducidos;
//        HashMap<String, Object> hashCliente = armarHashCliente();
//
//        //Realiza la verdadera busqueda
//        this.clientes = ControladorCliente.getInstancia().buscar(hashCliente);
//
//        //Cargar la busqueda en la JTable
//        cargarJTableCliente(clientes);
//
//        limpiarCampos(jpGeneralCliente);
//        limpiarCampos(jpDomicilioCliente);
//        jepDetalleCliente.setText("");
    }//GEN-LAST:event_jbBuscarClienteMouseClicked

    private void jtClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtClienteMouseClicked
//        //Carga el cliente seleccionado en la jTable en los textFields
//        cargarCamposCliente(clientes.get(jtCliente.getSelectedRow()));
    }//GEN-LAST:event_jtClienteMouseClicked

    private void tfNumeroTelefonoClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNumeroTelefonoClienteFocusLost
}//GEN-LAST:event_tfNumeroTelefonoClienteFocusLost

    private void jbNuevoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbNuevoClienteMouseClicked
    }//GEN-LAST:event_jbNuevoClienteMouseClicked

    private void jbModificarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbModificarClienteMouseClicked
//        //Modifica el ultimo cliente seleccionado
//        ControladorCliente.getInstancia().actualizar(cargarCliente(ultimoCliente));
//
//
//        limpiarCampos(jpGeneralCliente);
//        limpiarCampos(jpDomicilioCliente);
//        jepDetalleCliente.setText("");
    }//GEN-LAST:event_jbModificarClienteMouseClicked

    private void jbEliminarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEliminarClienteMouseClicked
//        //eliminar el ultimo cliente seleccionado
//        ControladorCliente.getInstancia().borrar(ultimoCliente);
    }//GEN-LAST:event_jbEliminarClienteMouseClicked

    private void jbLimpiarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarClienteActionPerformed
//        limpiarCampos(jpGeneralCliente);
//        limpiarCampos(jpDomicilioCliente);
//        jepDetalleCliente.setText("");
    }//GEN-LAST:event_jbLimpiarClienteActionPerformed

    private void jbNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoClienteActionPerformed
        String msg;

        //Crea una hash con todos los datos del cliente introducidos
        Cliente cliente = armarCliente();

        //Si se ha ingresado un nombre de cliente
        if (!(cliente.getNombre().equals("") || cliente.getCodigo().equals(""))) {

            //Se intenta grabar un vendedor en la Base de Datos
            msg = ControladorCliente.getInstancia().ingresar(cliente);

            //Si se produce un error mostrar el dialogo de error
            if (!(msg.equals(""))) {
                JOptionPane.showMessageDialog(null, msg, "ERROR", JOptionPane.ERROR_MESSAGE);
            } //Sino limpiar los campos
            else {
                JOptionPane.showMessageDialog(null, "Cliente ingresado con exito.", "Alta Cliente", JOptionPane.INFORMATION_MESSAGE);

//                limpiarCampos(jpGeneralCliente);
//                limpiarCampos(jpDomicilioCliente);
                jepDetalleCliente.setText("");

            }
        } //Sino muestra un dialogo de error
        else {
            JOptionPane.showMessageDialog(null, "Falta ingresar datos", "Alta Cliente", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbNuevoClienteActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbCondicionIvaCliente;
    private javax.swing.JComboBox cbEstadoDescuentoCliente;
    private javax.swing.JComboBox cbLocalidadCliente;
    private javax.swing.JComboBox cbPaisCliente;
    private javax.swing.JComboBox cbProvinciaCliente;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JButton jbBuscarCliente;
    private javax.swing.JButton jbEliminarCliente;
    private javax.swing.JButton jbImprimirCliente;
    private javax.swing.JButton jbLimpiarCliente;
    private javax.swing.JButton jbModificarCliente;
    private javax.swing.JButton jbNuevoCliente;
    private javax.swing.JButton jbOpcionesCliente;
    private javax.swing.JButton jbVenderCliente;
    private javax.swing.JEditorPane jepDetalleCliente;
    private javax.swing.JPanel jpCliente;
    private javax.swing.JPanel jpDetalleCliente;
    private javax.swing.JPanel jpDomicilioCliente;
    private javax.swing.JPanel jpGeneralCliente;
    private javax.swing.JScrollPane jspTablaCliente;
    private javax.swing.JTable jtCliente;
    private javax.swing.JTabbedPane jtpCliente;
    private javax.swing.JPanel pbCliente;
    private javax.swing.JSplitPane spCliente;
    private javax.swing.JTextField tfBuscarCliente;
    private javax.swing.JTextField tfCalleCliente;
    private javax.swing.JFormattedTextField tfCodigoCliente;
    private javax.swing.JTextField tfCuitCliente;
    private javax.swing.JTextField tfDeptoCliente;
    private javax.swing.JTextField tfDescuentoCliente;
    private javax.swing.JTextField tfMailCliente;
    private javax.swing.JFormattedTextField tfNombreCliente;
    private javax.swing.JTextField tfNumeroCliente;
    private javax.swing.JTextField tfNumeroTelefonoCliente;
    private javax.swing.JTextField tfPisoCliente;
    // End of variables declaration//GEN-END:variables

    private Cliente armarCliente() {

        Cliente c = new Cliente();

        c.setCodigo(tfCodigoCliente.getText());
        c.setNombre(tfNombreCliente.getText());
        c.setCuit(tfCuitCliente.getText());
        c.setMail(tfMailCliente.getText());
        c.setDescuento(Double.parseDouble(tfDescuentoCliente.getText()));
        c.setCondicionIva(cbCondicionIvaCliente.getSelectedItem().toString());

        return c;

    }
}
