/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelUsuarios.java
 *
 * Created on 24-mar-2010, 19:17:17
 */

package vete.Interfaz;

/**
 *
 * @author Silvina
 */
public class PanelUsuarios extends javax.swing.JPanel {

    /** Creates new form PanelUsuarios */
    public PanelUsuarios() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jpUsuario = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        tfNombreUsuario = new javax.swing.JTextField();
        jpfContraseniaUsuario = new javax.swing.JPasswordField();
        jLabel33 = new javax.swing.JLabel();
        cbPerfilUsuario = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        jbNuevoUsuario = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jbBuscarUsuario = new javax.swing.JButton();
        jpPerfiles = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        tfNombrePerfil = new javax.swing.JTextField();
        tfDescripcionPerfil = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        cbObjeto = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jcbLeer = new javax.swing.JCheckBox();
        jcbInsertar = new javax.swing.JCheckBox();
        jcbActualizar = new javax.swing.JCheckBox();
        jcbBorrar = new javax.swing.JCheckBox();
        jbAsignarPermiso = new javax.swing.JButton();
        jbNuevoPerfil = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jbBuscarPerfil = new javax.swing.JButton();

        jpUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios"));

        jLabel32.setText("Usuario");

        jLabel33.setText("Contraseña");

        cbPerfilUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel34.setText("Perfil");

        jbNuevoUsuario.setText("Nuevo");
        jbNuevoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbNuevoUsuarioMouseClicked(evt);
            }
        });

        jButton9.setText("Modificar");

        jButton10.setText("Eliminar");

        jbBuscarUsuario.setText("Buscar");
        jbBuscarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbBuscarUsuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpUsuarioLayout = new javax.swing.GroupLayout(jpUsuario);
        jpUsuario.setLayout(jpUsuarioLayout);
        jpUsuarioLayout.setHorizontalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpUsuarioLayout.createSequentialGroup()
                        .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpfContraseniaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbBuscarUsuario)
                                .addComponent(cbPerfilUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpUsuarioLayout.createSequentialGroup()
                        .addComponent(jbNuevoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpUsuarioLayout.setVerticalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpfContraseniaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPerfilUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevoUsuario)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jbBuscarUsuario))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jpPerfiles.setBorder(javax.swing.BorderFactory.createTitledBorder("Perfiles"));
        jpPerfiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpPerfilesMouseClicked(evt);
            }
        });

        jLabel35.setText("Perfil");

        jLabel36.setText("Descripcion");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Permisos"));

        jLabel46.setText("Objetos");

        cbObjeto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Clientes", "Articulos", "Proveedores", "Vender", "Comprar", "Configurar", "Usuarios" }));
        cbObjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbObjetoMouseClicked(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jcbLeer.setText("Consultar");
        jcbLeer.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jcbLeer.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jcbInsertar.setText("Agregar");
        jcbInsertar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jcbInsertar.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jcbActualizar.setText("Modificar");
        jcbActualizar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jcbActualizar.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jcbBorrar.setText("Eliminar");
        jcbBorrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jcbBorrar.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jcbLeer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbInsertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbBorrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jcbLeer)
                .addComponent(jcbInsertar)
                .addComponent(jcbActualizar)
                .addComponent(jcbBorrar))
        );

        jbAsignarPermiso.setText("Asignar");
        jbAsignarPermiso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAsignarPermisoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbObjeto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jbAsignarPermiso))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbAsignarPermiso)
                        .addComponent(cbObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbNuevoPerfil.setText("Nuevo");
        jbNuevoPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbNuevoPerfilMouseClicked(evt);
            }
        });

        jButton13.setText("Modificar");

        jButton14.setText("Eliminar");

        jbBuscarPerfil.setText("Buscar");
        jbBuscarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbBuscarPerfilMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpPerfilesLayout = new javax.swing.GroupLayout(jpPerfiles);
        jpPerfiles.setLayout(jpPerfilesLayout);
        jpPerfilesLayout.setHorizontalGroup(
            jpPerfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPerfilesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPerfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPerfilesLayout.createSequentialGroup()
                        .addGroup(jpPerfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNombrePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpPerfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(tfDescripcionPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPerfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpPerfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbNuevoPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jbBuscarPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpPerfilesLayout.setVerticalGroup(
            jpPerfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPerfilesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPerfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpPerfilesLayout.createSequentialGroup()
                        .addGroup(jpPerfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpPerfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNombrePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDescripcionPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPerfilesLayout.createSequentialGroup()
                        .addComponent(jbNuevoPerfil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbBuscarPerfil)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpPerfiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jpPerfiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbNuevoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbNuevoUsuarioMouseClicked

        String msg;

        //Crea una hash con todos los datos del usuario introducidos
        HashMap<String, Object> hashUsuario = armarUsuario();

        //Si se han ingresado los datos del usuario
        if (!(hashUsuario.get("nombre").equals("") || hashUsuario.get("contrasenia").equals("") || hashUsuario.get("perfil").equals(""))){

            //Se intenta grabar un usuario en la Base de Datos
            msg = ControladorSeguridad.getInstancia().ingresarUsuario(hashUsuario);

            //Si se produce un error mostrar el dialogo de error
            if (!(msg.equals(""))){
                JOptionPane.showMessageDialog(null, msg,"ERROR", JOptionPane.ERROR_MESSAGE);
            }
            //Sino limpiar los campos
            else {
                JOptionPane.showMessageDialog(null, "Usuario ingresado con exito.","Alta Usuario", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos(jpUsuario);
            }
        }

        //Sino muestra un dialogo de error
        else {
            JOptionPane.showMessageDialog(null, "Falta ingresar datos","Alta Usuario", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_jbNuevoUsuarioMouseClicked

    private void jbBuscarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbBuscarUsuarioMouseClicked

        //Verifica que el nombre de usuario no sea nulo
        if (tfNombreUsuario.getText()==null) {
            tfNombreUsuario.setText("");
        }

        //Crea una hash con los datos del usuario
        //this.objetos = usuarioAObjeto(ControladorSeguridad.getInstancia().buscarUsuario(armarUsuario()));
        this.objetos = aObjeto(ControladorSeguridad.getInstancia().buscarUsuario(armarUsuario()));

        //Carga la busqueda
        Buscar buscar = new Buscar(objetos);
        limpiarCampos(jpUsuario);
        buscar.setVisible(true);
        //buscar.cargarUsuarios(usuarios);

        tfNombreUsuario.setText(ultimoUsuario.getNombre());
        jpfContraseniaUsuario.setText(ultimoUsuario.getContrasenia());
        //cbPerfilUsuario.setSelectedItem(ultimoUsuario.getPerfil().toString());

    }//GEN-LAST:event_jbBuscarUsuarioMouseClicked

    private void cbObjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbObjetoMouseClicked

        List<Perfil> perfiles = null;
        List<Permiso> permisos = null;

        if (!(ultimoPerfil == null)) {

            perfiles = ControladorSeguridad.getInstancia().buscarPerfil(ultimoPerfil);
            permisos = perfiles.get(0).getPermisos();

            if (!(permisos == null)) {

                for (int i = 0; i <= permisos.size() - 1; i++) {

                    if ( permisos.get(i).getObjeto().equals( cbObjeto.getSelectedItem().toString() ) ) {

                        jcbLeer.setSelected(permisos.get(i).getLeer());
                        jcbInsertar.setSelected(permisos.get(i).getInsertar());
                        jcbActualizar.setSelected(permisos.get(i).getActualizar());
                        jcbBorrar.setSelected(permisos.get(i).getBorrar());

                    }
                }
            }
        }
}//GEN-LAST:event_cbObjetoMouseClicked

    private void jbAsignarPermisoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAsignarPermisoMouseClicked

        List<Permiso> permisos;
        Permiso permiso = new Permiso();

        permiso.setObjeto(cbObjeto.getSelectedItem().toString() == null ? "" : cbObjeto.getSelectedItem().toString());
        permiso.setLeer(jcbLeer.isSelected());
        permiso.setInsertar(jcbInsertar.isSelected());
        permiso.setActualizar(jcbActualizar.isSelected());
        permiso.setBorrar(jcbBorrar.isSelected());

        permisos = ultimoPerfil.getPermisos();
        permisos.setElementAt(permiso, cbObjeto.getSelectedIndex());
        ultimoPerfil.setPermisos(permisos);

    }//GEN-LAST:event_jbAsignarPermisoMouseClicked

    private void jbNuevoPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbNuevoPerfilMouseClicked

        String msg;

        //Crea una hash con todos los datos del perfil introducidos
        HashMap<String, Object> hashPerfil = armarHashPerfil();

        //Si se han ingresado los datos del perfil
        if (!(hashPerfil.get("nombre").equals("") )){

            //Se intenta grabar un perfil en la Base de Datos
            msg = ControladorSeguridad.getInstancia().ingresarPerfil(hashPerfil);

            //Si se produce un error mostrar el dialogo de error
            if (!(msg.equals(""))){
                JOptionPane.showMessageDialog(null, msg,"ERROR", JOptionPane.ERROR_MESSAGE);
            }
            //Sino limpiar los campos
            else {
                JOptionPane.showMessageDialog(null, "Perfil ingresado con exito.","Alta Perfil", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos(jpPerfiles);
            }
        }

        //Sino muestra un dialogo de error
        else {
            JOptionPane.showMessageDialog(null, "Falta ingresar datos","Alta Usuario", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbNuevoPerfilMouseClicked

    private void jbBuscarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbBuscarPerfilMouseClicked

        Perfil perfil = new Perfil();
        perfil.setNombre(tfNombrePerfil.getText() == null ? "" : tfNombrePerfil.getText()));

        //Realiza la verdadera busqueda
        //this.objetos = perfilAObjeto(ControladorSeguridad.getInstancia().buscarPerfil(hashPerfil));
        this.objetos = aObjeto(ControladorSeguridad.getInstancia().buscarPerfil(perfil));

        //Cargar la busqueda
        Buscar buscar = new Buscar(objetos);
        limpiarCampos(jpPerfiles);
        buscar.setVisible(true);
        //buscar.cargarPerfiles(perfiles);

        tfNombrePerfil.setText(ultimoPerfil.getNombre());
        tfDescripcionPerfil.setText(ultimoPerfil.getDescipcion());
}//GEN-LAST:event_jbBuscarPerfilMouseClicked

    private void jpPerfilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPerfilesMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_jpPerfilesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbObjeto;
    private javax.swing.JComboBox cbPerfilUsuario;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jbAsignarPermiso;
    private javax.swing.JButton jbBuscarPerfil;
    private javax.swing.JButton jbBuscarUsuario;
    private javax.swing.JButton jbNuevoPerfil;
    private javax.swing.JButton jbNuevoUsuario;
    private javax.swing.JCheckBox jcbActualizar;
    private javax.swing.JCheckBox jcbBorrar;
    private javax.swing.JCheckBox jcbInsertar;
    private javax.swing.JCheckBox jcbLeer;
    private javax.swing.JPanel jpPerfiles;
    private javax.swing.JPanel jpUsuario;
    private javax.swing.JPasswordField jpfContraseniaUsuario;
    private javax.swing.JTextField tfDescripcionPerfil;
    private javax.swing.JTextField tfNombrePerfil;
    private javax.swing.JTextField tfNombreUsuario;
    // End of variables declaration//GEN-END:variables

}
